/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package perpus;

import org.apache.pdfbox.Loader;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.rendering.PDFRenderer;

import javax.swing.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.awt.*;

/**
 *
 * @author Haikal
 */
public class PDFReaderFrame extends javax.swing.JFrame {
    private PDDocument document;
    private PDFRenderer renderer;
    private int pageIndex = 0;
    private float zoomFactor = 1.0f;

    private JLabel lblPage;
    private JButton btnPrev;
    private JButton btnNext;
    private JButton btnZoomIn;
    private JButton btnZoomOut;
    private JButton btnFit;

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PDFReaderFrame.class.getName());

    /**
     * Creates new form PDFReaderFrame
     */
    public PDFReaderFrame(String pathPdf) {
        initComponents();
        setIconImage(
        Toolkit.getDefaultToolkit().getImage(
            getClass().getResource("/perpus/icon.png")
        )
    );
        setTitle("PDF Reader");
        setSize(800, 600);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        lblPage = new JLabel();
        btnPrev = new JButton("Prev");
        btnNext = new JButton("Next");
        btnZoomIn = new JButton("+");
        btnZoomOut = new JButton("-");
        btnFit = new JButton("Fit");


        JScrollPane scroll = new JScrollPane(lblPage);

        JPanel nav = new JPanel();
        nav.add(btnPrev);
        nav.add(btnNext);
        nav.add(btnZoomOut);
        nav.add(btnZoomIn);
        nav.add(btnFit);

        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().add(scroll, java.awt.BorderLayout.CENTER);
        getContentPane().add(nav, java.awt.BorderLayout.SOUTH);

        try {
            document = Loader.loadPDF(new File(pathPdf));
            renderer = new PDFRenderer(document);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal membuka PDF");
            dispose();
            return;
        }

        btnPrev.addActionListener(e -> showPage(pageIndex - 1));
        btnNext.addActionListener(e -> showPage(pageIndex + 1));
        btnZoomIn.addActionListener(e -> {
            zoomFactor += 0.2f;
            showPage(pageIndex);
        });

        btnZoomOut.addActionListener(e -> {
            if (zoomFactor > 0.4f) {
                zoomFactor -= 0.2f;
                showPage(pageIndex);
            }
        });

        btnFit.addActionListener(e -> fitToWindow());


        showPage(0);
    }
    
    private void showPage(int index) {
        try {
            if (index < 0 || index >= document.getNumberOfPages()) return;

            pageIndex = index;
            float dpi = 120 * zoomFactor;

            BufferedImage img = renderer.renderImageWithDPI(pageIndex, dpi);
            lblPage.setIcon(new ImageIcon(img));
            lblPage.revalidate();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void fitToWindow() {
        try {
            float pageWidth = document.getPage(pageIndex)
                    .getMediaBox().getWidth();

            JScrollPane scroll = (JScrollPane) lblPage.getParent().getParent();
            int viewportWidth = scroll.getViewport().getWidth();

            zoomFactor = viewportWidth / pageWidth;
            showPage(pageIndex);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
